# Generated by Django 5.2.4 on 2025-07-23 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="alcohol_strength",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sourness_level",
        ),
        migrations.RemoveField(
            model_name="product",
            name="umami_level",
        ),
        migrations.AddField(
            model_name="product",
            name="acidity_level",
            field=models.FloatField(
                default=0.0,
                help_text="산미 지수 (0.0 ~ 5.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="aroma_level",
            field=models.FloatField(
                default=0.0,
                help_text="향 지수 (0.0 ~ 5.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="carbonation_level",
            field=models.FloatField(
                default=0.0,
                help_text="탄산감 (0.0 ~ 5.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="bitterness_level",
            field=models.FloatField(
                default=0.0,
                help_text="쓴맛:누룩맛 지수 (0.0 ~ 5.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
