# Generated by Django 5.2.4 on 2025-08-07 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="liked_products", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="drink",
            index=models.Index(fields=["name"], name="drinks_name_1aa907_idx"),
        ),
        migrations.AddIndex(
            model_name="drink",
            index=models.Index(fields=["alcohol_type"], name="drinks_alcohol_a6c71a_idx"),
        ),
        migrations.AddIndex(
            model_name="drink",
            index=models.Index(fields=["alcohol_content"], name="drinks_alcohol_cd97e5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="packageitem",
            unique_together={("drink", "package")},
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["type"], name="packages_type_845790_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["name"], name="packages_name_2c850c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_price_fe467e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="products_status_a30e64_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-created_at"], name="products_created_a77fb9_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-view_count"], name="products_view_co_181adc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-order_count"], name="products_order_c_dbafa9_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product", "is_main"], name="product_ima_product_1fb2a2_idx"),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)), fields=("product",), name="unique_main_image_per_product"
            ),
        ),
        migrations.AddIndex(
            model_name="productlike",
            index=models.Index(fields=["user"], name="product_lik_user_id_24f108_idx"),
        ),
        migrations.AddIndex(
            model_name="productlike",
            index=models.Index(fields=["product"], name="product_lik_product_ce3d9c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productlike",
            unique_together={("user", "product")},
        ),
    ]
