# Generated by Django 5.2.4 on 2025-08-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="drink",
            name="drinks_alcohol_cd97e5_idx",
        ),
        migrations.RenameField(
            model_name="brewery",
            old_name="image",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="drink",
            old_name="alcohol_content",
            new_name="abv",
        ),
        migrations.AddIndex(
            model_name="drink",
            index=models.Index(fields=["abv"], name="drinks_abv_00bf56_idx"),
        ),
    ]
