# Generated by Django 5.2.4 on 2025-08-09 11:07

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_drink_drinks_alcohol_cd97e5_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brewery",
            name="address",
            field=models.TextField(blank=True, help_text="주소", null=True),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="description",
            field=models.TextField(blank=True, help_text="양조장 설명", null=True),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="image_url",
            field=models.URLField(blank=True, help_text="양조장 이미지 URL", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="is_active",
            field=models.BooleanField(default=True, help_text="활성 상태"),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="name",
            field=models.CharField(help_text="양조장명", max_length=100),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="phone",
            field=models.CharField(blank=True, help_text="연락처", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="region",
            field=models.CharField(blank=True, help_text="지역", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="drink",
            name="abv",
            field=models.DecimalField(
                decimal_places=2,
                help_text="알코올 도수(%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="acidity_level",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="산미 (0.0~5.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="aroma_level",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="풍미 (0.0~5.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="bitterness_level",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="쓴맛 (0.0~5.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="body_level",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="바디감 (0.0~5.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="carbonation_level",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="탄산감 (0.0~5.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="name",
            field=models.CharField(help_text="술 이름", max_length=100),
        ),
        migrations.AlterField(
            model_name="drink",
            name="sweetness_level",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="단맛 (0.0~5.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(help_text="패키지명", max_length=30),
        ),
        migrations.AlterField(
            model_name="package",
            name="type",
            field=models.CharField(
                choices=[("CURATED", "큐레이티드"), ("MY_CUSTOM", "마이 커스텀")],
                default="CURATED",
                help_text="패키지 타입",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="상품 설명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_image_url",
            field=models.URLField(help_text="상품 설명 이미지 URL", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="drink",
            field=models.OneToOneField(
                blank=True,
                help_text="개별 술",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.drink",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_award_winning",
            field=models.BooleanField(default=False, help_text="수상작"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_gift_suitable",
            field=models.BooleanField(default=False, help_text="선물 적합"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_limited_edition",
            field=models.BooleanField(default=False, help_text="리미티드 에디션"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_organic",
            field=models.BooleanField(default=False, help_text="유기농"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_premium",
            field=models.BooleanField(default=False, help_text="프리미엄"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_regional_specialty",
            field=models.BooleanField(default=False, help_text="지역 특산주"),
        ),
        migrations.AlterField(
            model_name="product",
            name="like_count",
            field=models.PositiveIntegerField(default=0, help_text="좋아요 수"),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_count",
            field=models.PositiveIntegerField(default=0, help_text="주문수"),
        ),
        migrations.AlterField(
            model_name="product",
            name="package",
            field=models.OneToOneField(
                blank=True,
                help_text="패키지",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.package",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(default=0, help_text="리뷰 수"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "활성"), ("INACTIVE", "비활성"), ("OUT_OF_STOCK", "품절")],
                default="ACTIVE",
                help_text="상태",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(default=0, help_text="조회수"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(help_text="이미지 URL", max_length=255),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, help_text="메인 이미지 여부"),
        ),
    ]
