# Generated by Django 5.2.4 on 2025-08-12 07:24

from decimal import Decimal  # Import Decimal

from django.db import migrations


def create_initial_products(apps, schema_editor):
    Brewery = apps.get_model("products", "Brewery")
    Drink = apps.get_model("products", "Drink")
    Package = apps.get_model("products", "Package")
    Product = apps.get_model("products", "Product")
    ProductImage = apps.get_model("products", "ProductImage")  # Also need ProductImage

    # Create a Brewery
    brewery = Brewery.objects.create(name="한잔 양조장")

    # Create a Drink
    drink = Drink.objects.create(
        name="한잔 막걸리",
        brewery=brewery,
        ingredients="쌀, 누룩, 물",
        alcohol_type="MAKGEOLLI",
        abv=Decimal("6.0"),
        volume_ml=750,
    )

    # Create a Package
    curated_package = Package.objects.create(name="한잔 추천 세트", type="CURATED")

    # Create Product instances
    product_drink = Product.objects.create(
        drink=drink,
        price=15000,
        description="깊은 맛의 전통 막걸리",
    )
    ProductImage.objects.create(
        product=product_drink, image_url="https://example.com/hanjan_makgeolli.jpg", is_main=True
    )

    product_package = Product.objects.create(
        package=curated_package,
        price=30000,
        description="특별한 날을 위한 한잔 세트",
    )
    ProductImage.objects.create(
        product=product_package, image_url="https://example.com/hanjan_package.jpg", is_main=True
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_alter_brewery_address_alter_brewery_description_and_more",
        ),  # Dependency on the previous product migration
    ]

    operations = [
        migrations.RunPython(create_initial_products),
    ]
