# Generated by Django 5.2.4 on 2025-08-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("delivery_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_id", models.CharField(help_text="주문 번호 (예: ORD20250722001)", max_length=20)),
                ("product_name", models.CharField(help_text="배송되는 상품명", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "배송 준비 중"),
                            ("shipping", "배송 중"),
                            ("delivered", "배송 완료"),
                            ("cancelled", "배송 취소"),
                        ],
                        default="pending",
                        help_text="배송 상태",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, help_text="송장 번호", max_length=50, null=True)),
                ("courier", models.CharField(blank=True, help_text="택배사 이름", max_length=50, null=True)),
                ("estimated_arrival", models.DateField(blank=True, help_text="예상 도착일", null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="배송 정보 마지막 업데이트 시간")),
            ],
            options={
                "db_table": "delivery",
            },
        ),
    ]
