# Generated by Django 5.2.4 on 2025-07-30 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_remove_product_alcohol_strength_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_price", models.DecimalField(decimal_places=0, max_digits=10, verbose_name="총 가격")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("processing", "처리중"),
                            ("shipped", "배송중"),
                            ("delivered", "배송완료"),
                            ("cancelled", "취소됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="주문 상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="주문일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주문자",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문",
                "verbose_name_plural": "주문 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(verbose_name="수량")),
                ("price", models.DecimalField(decimal_places=0, max_digits=10, verbose_name="단가")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="주문",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.product", verbose_name="상품"
                    ),
                ),
            ],
            options={
                "verbose_name": "주문 상품",
                "verbose_name_plural": "주문 상품 목록",
                "unique_together": {("order", "product")},
            },
        ),
    ]
