# Generated by Django 5.2.4 on 2025-08-07 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_number", models.CharField(help_text="사용자에게 보여줄 주문 번호", max_length=20, unique=True)),
                ("total_price", models.PositiveIntegerField(help_text="총 주문 금액")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "주문 완료"),
                            ("CONFIRMED", "주문 확인"),
                            ("READY", "픽업 준비 완료"),
                            ("COMPLETED", "픽업 완료"),
                            ("CANCELLED", "주문 취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.PositiveIntegerField(help_text="주문 당시 상품 단가")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="주문 수량", validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("pickup_day", models.DateField(help_text="픽업 예정 날짜")),
                ("pickup_status", models.BooleanField(default=False, help_text="픽업 완료 여부")),
                ("is_gift", models.BooleanField(default=False, help_text="선물 포장 여부")),
                ("gift_message", models.TextField(blank=True, help_text="선물 메시지", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "order_items",
            },
        ),
    ]
