# Generated by Django 5.2.4 on 2025-08-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="gift_message",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="is_gift",
        ),
    ]
