# Generated by Django 5.2.4 on 2025-08-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreferenceTestResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answers", models.JSONField(help_text="테스트 답변 (예: {'q1': 'A', 'q2': 'B', 'q3': 'C'})")),
                (
                    "prefer_taste",
                    models.CharField(
                        choices=[
                            ("SWEET_FRUIT", "달콤과일파"),
                            ("FRESH_FIZZY", "상큼톡톡파"),
                            ("HEAVY_LINGERING", "묵직여운파"),
                            ("CLEAN_SAVORY", "깔끔고소파"),
                            ("FRAGRANT_NEAT", "향긋단정파"),
                            ("FRESH_CLEAN", "상큼깔끔파"),
                            ("HEAVY_SWEET", "묵직달콤파"),
                            ("SWEET_SAVORY", "달콤고소파"),
                            ("GOURMET", "미식가유형"),
                        ],
                        help_text="분석된 취향 유형",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "preference_test_results",
            },
        ),
    ]
