# Generated by Django 5.2.4 on 2025-08-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taste_test", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preferencetestresult",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference_test_result",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="preferencetestresult",
            index=models.Index(fields=["prefer_taste"], name="preference__prefer__6f5c3b_idx"),
        ),
        migrations.AddIndex(
            model_name="preferencetestresult",
            index=models.Index(fields=["created_at"], name="preference__created_1b191f_idx"),
        ),
        migrations.AddIndex(
            model_name="preferencetestresult",
            index=models.Index(fields=["-created_at"], name="preference__created_1c4777_idx"),
        ),
    ]
