# Generated by Django 5.2.4 on 2025-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taste_test", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="preferencetestresult",
            name="preference__created_1b191f_idx",
        ),
        migrations.AlterField(
            model_name="preferencetestresult",
            name="answers",
            field=models.JSONField(help_text="테스트 답변 (예: {'Q1': 'A', 'Q2': 'B', 'Q3': 'C'})"),
        ),
    ]
