# Generated by Django 5.2.4 on 2025-07-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "verbose_name": "장바구니",
                "verbose_name_plural": "장바구니 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "장바구니 상품",
                "verbose_name_plural": "장바구니 상품 목록",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
    ]
