# Generated by Django 5.2.4 on 2025-08-07 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["user"], name="cart_items_user_id_2651f6_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="cart_items_product_6a1de7_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["created_at"], name="cart_items_created_71da0d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("user", "product")},
        ),
    ]
