# Generated by Django 5.2.4 on 2025-08-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "장바구니 항목",
                "verbose_name_plural": "장바구니 항목 목록",
            },
        ),
    ]
