# Generated by Django 5.2.4 on 2025-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cart_customer_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="pickup_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="픽업 일시"),
        ),
        migrations.AddField(
            model_name="cart",
            name="pickup_store_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="픽업 매장 이름"),
        ),
        migrations.AddField(
            model_name="cart",
            name="pickup_store_phone",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="매장 전화번호"),
        ),
    ]
