# Generated by Django 5.2.4 on 2025-08-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cartitem_options"),
        ("stores", "0002_auto_20250812_0606"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="pickup_date",
            field=models.DateField(blank=True, help_text="픽업 날짜", null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="pickup_store",
            field=models.ForeignKey(
                blank=True,
                help_text="픽업 매장",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items_for_pickup",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, help_text="수량"),
        ),
    ]
