# Generated by Django 5.2.4 on 2025-07-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_cart_pickup_datetime_cart_pickup_store_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="pickup_datetime",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="pickup_store_name",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="pickup_store_phone",
        ),
    ]
