# Generated by Django 5.2.4 on 2025-08-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cartitem_quantity"),
        ("cart", "0005_cartitem_pickup_date_cartitem_pickup_store_and_more"),
    ]

    operations = []
