# Generated by Django 5.2.4 on 2025-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_remove_cart_pickup_datetime_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="package_group",
            field=models.UUIDField(blank=True, null=True, verbose_name="패키지 그룹 ID"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="수량"),
        ),
    ]
