# Generated by Django 5.2.4 on 2025-08-18 04:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_merge_20250813_1549"),
        ("products", "0005_auto_20250812_0724"),
        ("stores", "0006_alter_storelike_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("user", "product", "pickup_store", "pickup_date")},
        ),
    ]
