# Generated by Django 5.2.4 on 2025-08-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_cart_user_not_null"),
        ("products", "0002_remove_product_alcohol_strength_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="package_group",
        ),
    ]
