# Generated by Django 5.2.4 on 2025-08-05 01:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_cartitem_unique_together_alter_cart_id_and_more"),
        ("products", "0002_remove_product_alcohol_strength_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["added_at"],
                "verbose_name": "장바구니 상품",
                "verbose_name_plural": "장바구니 상품 목록",
            },
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="추가된 시간"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="개별 상품",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="수량"),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("cart", "product"),
                name="unique_product_in_cart",
            ),
        ),
    ]
