# Generated by Django 5.2.4 on 2025-08-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_product_in_cart",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="item_type",
            field=models.CharField(
                choices=[("PRODUCT", "개별 상품"), ("CUSTOM_TRIO", "맞춤 3종 세트")],
                default="PRODUCT",
                max_length=20,
                verbose_name="항목 유형",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="추가된 시간"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="cart.cart"),
        ),
    ]
