# Generated by Django 5.2.4 on 2025-08-07 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="평점 (1-5점)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="신뢰도 (0-100%) - 사용자가 자신의 입맛 정확도를 설정",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, help_text="상세 피드백 내용", null=True)),
                (
                    "selected_tags",
                    models.JSONField(
                        blank=True,
                        help_text="선택한 맛/느낌 태그들 (예: ['달콤해요', '목넘김이 좋아요', '향이 좋아요'])",
                        null=True,
                    ),
                ),
                ("verified_purchase", models.BooleanField(default=True, help_text="구매 인증 여부")),
                ("view_count", models.PositiveIntegerField(default=0, help_text="피드백 조회수")),
                ("last_viewed_at", models.DateTimeField(blank=True, help_text="마지막 조회 일시", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "feedbacks",
            },
        ),
    ]
