# Generated by Django 5.2.4 on 2025-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="detailed_comment",
            field=models.TextField(blank=True, verbose_name="상세 후기"),
        ),
    ]
