# Generated by Django 5.2.4 on 2025-08-07 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedback", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="order_item",
            field=models.OneToOneField(
                help_text="피드백을 작성한 주문 아이템",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="orders.orderitem",
            ),
        ),
    ]
