# Generated by Django 5.2.4 on 2025-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_detailed_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="taste_tags",
            field=models.CharField(
                blank=True, help_text="쉼표로 구분된 문자열 (예: 단맛,과일향)", max_length=255, verbose_name="맛 태그"
            ),
        ),
    ]
