# Generated by Django 5.2.4 on 2025-08-07 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedback", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["user", "created_at"], name="feedbacks_user_id_c7b83f_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["rating"], name="feedbacks_rating_109b6e_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["order_item"], name="feedbacks_order_i_797fa2_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["rating", "created_at"], name="feedbacks_rating_efe1c7_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["user", "rating"], name="feedbacks_user_id_bdc708_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["created_at", "view_count"], name="feedbacks_created_425bcf_idx"),
        ),
    ]
