# Generated by Django 5.2.4 on 2025-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_feedback_taste_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
