# Generated by Django 5.2.4 on 2025-08-13 05:40

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_initial"),
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedbacks_user_id_bdc708_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedbacks_created_425bcf_idx",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="verified_purchase",
        ),
        migrations.AddField(
            model_name="feedback",
            name="acidity",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="산미 평가 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="aroma",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="풍미 평가 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="bitterness",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="쓴맛 평가 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="body",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="바디감 평가 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="carbonation",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="탄산감 평가 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="sweetness",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="단맛 평가 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveIntegerField(
                help_text="종합 평점 (1-5점)",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="selected_tags",
            field=models.JSONField(
                blank=True, help_text="선택한 맛/느낌 태그들 (예: ['과일향', '달콤한', '부드러운'])", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["sweetness", "acidity", "body"], name="feedbacks_sweetne_d7f71f_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["carbonation", "bitterness", "aroma"], name="feedbacks_carbona_778c82_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["view_count"], name="feedbacks_view_co_5fab60_idx"),
        ),
    ]
