# Generated by Django 5.2.4 on 2025-08-05 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedback_view_count"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="taste_tags",
        ),
        migrations.AddField(
            model_name="feedback",
            name="days_after_purchase",
            field=models.IntegerField(blank=True, null=True, verbose_name="구매 후 경과일"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="selected_tags",
            field=models.JSONField(blank=True, null=True, verbose_name="선택된 맛 태그"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="acidity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="body",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.TextField(blank=True, verbose_name="한 줄 평"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="confidence",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="orders.orderitem"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="overall_rating",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="photo_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="sweetness",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
