# Generated by Django 5.2.4 on 2025-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_remove_feedback_feedbacks_user_id_bdc708_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="image_url",
            field=models.URLField(blank=True, help_text="피드백 이미지 URL (S3/NCP 저장소)", max_length=500, null=True),
        ),
    ]
