# Generated by Django 5.2.4 on 2025-08-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prefertasteprofile",
            name="is_initialized",
        ),
        migrations.AddField(
            model_name="prefertasteprofile",
            name="analysis_description",
            field=models.TextField(blank=True, help_text="취향 분석 설명"),
        ),
        migrations.AddField(
            model_name="prefertasteprofile",
            name="analysis_updated_at",
            field=models.DateTimeField(blank=True, help_text="분석 마지막 업데이트 시간", null=True),
        ),
    ]
