# Generated by Django 5.2.4 on 2025-08-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_prefertasteprofile_is_initialized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefertasteprofile",
            name="last_retake_at",
            field=models.DateTimeField(blank=True, help_text="마지막 재테스트 일시", null=True),
        ),
        migrations.AddField(
            model_name="prefertasteprofile",
            name="last_retake_influence",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="마지막 재테스트 영향률", max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="prefertasteprofile",
            name="retake_base_scores",
            field=models.JSONField(blank=True, help_text="재테스트 기준점 (점진적 적용용)", null=True),
        ),
        migrations.AddField(
            model_name="prefertasteprofile",
            name="retake_count",
            field=models.PositiveIntegerField(default=0, help_text="재테스트 횟수"),
        ),
        migrations.AddIndex(
            model_name="prefertasteprofile",
            index=models.Index(fields=["last_retake_at"], name="prefer_tast_last_re_7445c4_idx"),
        ),
    ]
