# Generated by Django 5.2.4 on 2025-08-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = []
