# Generated by Django 5.2.4 on 2025-08-12 07:11

from django.db import migrations


def populate_initial_product_stock(apps, schema_editor):
    Store = apps.get_model("stores", "Store")
    Product = apps.get_model("products", "Product")
    ProductStock = apps.get_model("stores", "ProductStock")

    stores = Store.objects.all()
    products = Product.objects.all()

    for store in stores:
        for product in products:
            # Create or update ProductStock for each product in each store
            ProductStock.objects.update_or_create(store=store, product=product, defaults={"quantity": 10})


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_auto_20250812_0606"),  # Dependency on the previous store creation migration
        (
            "products",
            "0004_alter_brewery_address_alter_brewery_description_and_more",
        ),  # Dependency on a product migration to ensure Product model exists
    ]

    operations = [
        migrations.RunPython(populate_initial_product_stock),
    ]
