# Generated by Django 5.2.4 on 2025-08-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_auto_20250812_0606"),  # Dependency on the previous store creation migration
        (
            "products",
            "0004_alter_brewery_address_alter_brewery_description_and_more",
        ),  # Dependency on a product migration to ensure Product model exists
    ]

    operations = []
