# Generated by Django 5.2.4 on 2025-08-12 07:25

from django.db import migrations


def populate_initial_product_stock_again(apps, schema_editor):
    Store = apps.get_model("stores", "Store")
    Product = apps.get_model("products", "Product")
    ProductStock = apps.get_model("stores", "ProductStock")

    stores = Store.objects.all()
    products = Product.objects.all()

    for store in stores:
        for product in products:
            # Create or update ProductStock for each product in each store
            ProductStock.objects.update_or_create(store=store, product=product, defaults={"quantity": 10})


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_auto_20250812_0711"),  # Dependency on the previous stores migration
        ("products", "0005_auto_20250812_0724"),  # Dependency on the products migration that creates products
    ]

    operations = [
        migrations.RunPython(populate_initial_product_stock_again),
    ]
