# Generated by Django 5.2.4 on 2025-08-13 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_auto_20250812_0725"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="stores.store"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_likes",
            },
        ),
        migrations.DeleteModel(
            name="ProductStock",
        ),
        migrations.AddIndex(
            model_name="storelike",
            index=models.Index(fields=["user"], name="store_likes_user_id_4c4674_idx"),
        ),
        migrations.AddIndex(
            model_name="storelike",
            index=models.Index(fields=["store"], name="store_likes_store_i_d7b753_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="storelike",
            unique_together={("user", "store")},
        ),
    ]
