# Generated by Django 5.2.4 on 2025-08-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_storelike_delete_productstock_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storelike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="storelike",
            name="store",
        ),
        migrations.RemoveField(
            model_name="storelike",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="store",
            name="stores_status_ecb921_idx",
        ),
        migrations.RemoveIndex(
            model_name="store",
            name="stores_latitud_c3b239_idx",
        ),
        migrations.RemoveIndex(
            model_name="store",
            name="stores_has_tas_df887d_idx",
        ),
        migrations.RemoveIndex(
            model_name="store",
            name="stores_has_par_5e589f_idx",
        ),
        migrations.RemoveField(
            model_name="store",
            name="closed_days",
        ),
        migrations.RemoveField(
            model_name="store",
            name="has_parking",
        ),
        migrations.RemoveField(
            model_name="store",
            name="has_tasting",
        ),
        migrations.RemoveField(
            model_name="store",
            name="image",
        ),
        migrations.RemoveField(
            model_name="store",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="store",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="store",
            name="opening_days",
        ),
        migrations.RemoveField(
            model_name="store",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="store",
            name="status",
        ),
        migrations.DeleteModel(
            name="StoreLike",
        ),
    ]
